Repository zetsuchan/angstromscd-monorepo, pull requests merged in 2025-06, with the labels that each got.

#2 feat: integrate ollama
  bun.lock
  bun.lockb
  packages/baml/IMPLEMENTATION.md
  packages/baml/baml.config.ts
  packages/baml/baml_client/async_client.ts
  packages/baml/baml_client/async_request.ts
  packages/baml/baml_client/config.ts
  packages/baml/baml_client/globals.ts
  packages/baml/baml_client/index.ts
  packages/baml/baml_client/inlinedbaml.ts
  packages/baml/baml_client/parser.ts
  packages/baml/baml_client/partial_types.ts
  packages/baml/baml_client/sync_client.ts
  packages/baml/baml_client/sync_request.ts
  packages/baml/baml_client/tracing.ts
  packages/baml/baml_client/type_builder.ts
  packages/baml/baml_client/types.ts
  packages/baml/baml_src/clients.baml
  packages/baml/baml_src/templates/literature-search.baml
  packages/baml/baml_src/templates/medical-analysis.baml
  packages/baml/baml_src/templates/risk-modeling.baml
  packages/baml/bun.lock
  packages/baml/src/index.ts
  packages/baml/src/services/baml-service.ts
Labels: Review effort 3/5

#3 Fix flush syntax in baml tracing
  packages/baml/baml_client/tracing.ts
Labels: codex, Review effort 2/5

#4 Fix BAML client initialization check
  packages/baml/src/services/baml-service.ts
Labels: codex, Review effort 1/5

#5 Remove ts-nocheck from generated BAML client
  apps/api/package.json
  packages/baml/baml_client/async_client.ts
  packages/baml/baml_client/async_request.ts
  packages/baml/baml_client/config.ts
  packages/baml/baml_client/globals.ts
  packages/baml/baml_client/index.ts
  packages/baml/baml_client/inlinedbaml.ts
  packages/baml/baml_client/parser.ts
  packages/baml/baml_client/partial_types.ts
  packages/baml/baml_client/sync_client.ts
  packages/baml/baml_client/sync_request.ts
  packages/baml/baml_client/tracing.ts
  packages/baml/baml_client/type_builder.ts
  packages/baml/baml_client/types.ts
  packages/baml/package.json
  packages/vector/package.json
Labels: codex, Review effort 2/5

#7 Add monorepo overview
  README.md
Labels: codex, Review effort 1/5

#10 Codex/fix syntax error in flush function
  CLAUDE.md
  PRD-Local-AI-Models-Integration.md
  packages/apple-bridge/.gitignore
  packages/apple-bridge/Package.swift
  packages/apple-bridge/README.md
  packages/apple-bridge/Sources/AppleFoundationBridge/main.swift
  packages/baml/.env.example
  packages/baml/baml.config.ts
  packages/baml/baml_client/tracing.ts
  packages/baml/baml_src/clients.baml
  packages/baml/biome.json
  packages/baml/package.json
  packages/baml/src/index.ts
  packages/baml/src/services/baml-service.ts
  packages/baml/src/services/model-router.ts
  packages/baml/src/types/index.ts
  packages/baml/src/utils/response.ts
  packages/baml/tsconfig.json
Labels: Review effort 4/5

#12 docs: enhance CLAUDE.md with testing guidance and development patterns
  CLAUDE.md
Labels: Review effort 2/5

#14 feat: implement multi-provider vector database support
  CLAUDE.md
  bun.lockb
  infra/docker-compose.yml
  infra/scripts/init-pgvector.sql
  packages/apple-bridge/Package.resolved
  packages/apple-bridge/Package.swift
  packages/apple-bridge/README.md
  packages/apple-bridge/Sources/AppleFoundationBridge/AppleFoundationModelService.swift
  packages/apple-bridge/Sources/AppleFoundationBridge/Tools.swift
  packages/apple-bridge/Sources/AppleFoundationBridge/Types.swift
  packages/apple-bridge/Sources/AppleFoundationBridge/main.swift
  packages/apple-bridge/test-service.sh
  packages/vector/.env.example
  packages/vector/package.json
  packages/vector/src/index.ts
  packages/vector/src/interfaces/vector-provider.interface.ts
  packages/vector/src/services/chroma-provider.ts
  packages/vector/src/services/pgvector-provider.ts
  packages/vector/src/services/qdrant-provider.ts
  packages/vector/src/services/vector-provider-factory.ts
  packages/vector/src/services/vector-service.ts
  packages/vector/test-providers.ts
Labels: Review effort 4/5, Possible security concern

#16 Fix/pr 15 review issues
  apps/api/src/routes/index.ts
  apps/desktop-swift/Sources/AngstromSCD/Models/DataModels.swift
  apps/desktop-swift/Sources/AngstromSCD/Services/APIClient.swift
  apps/desktop-swift/Sources/AngstromSCD/Services/AppleFoundationService.swift
  apps/desktop-swift/Sources/AngstromSCD/Views/ContentView.swift
  apps/desktop-swift/Sources/AngstromSCD/Views/ConversationView.swift
  apps/desktop-swift/Sources/AngstromSCD/Views/DetailPaneView.swift
  apps/desktop-swift/Sources/AngstromSCD/Views/LiquidGlassView.swift
  apps/desktop-swift/Sources/AngstromSCD/Views/SettingsView.swift
  apps/desktop-swift/Sources/AngstromSCD/Views/SidebarView.swift
  apps/frontend/src/components/ErrorBoundary.tsx
  apps/frontend/src/components/chat/ChatBubble.tsx
  apps/frontend/src/context/ChatContext.tsx
  apps/frontend/src/lib/api-client.ts
  apps/frontend/src/main.tsx
  packages/vector/src/services/vector-provider-factory.ts
  packages/vector/test-providers.ts
Labels: Review effort 4/5, Possible security concern
